import { StyleSheet } from 'react-native'

export const signInStyles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#092C1A',
        padding: 20,
        width: '100%',
    },
    title: {
        fontSize: 50,
        fontWeight: 'bold',
        fontStyle: 'normal',
        color: '#C7F3D3',
        marginBottom: 40,
    },
    input: {
        height: 60,
        width: 250,
        color: '#C7F3D3',
        borderRadius: "12px",
        borderWidth: 1,
        padding: 10,
        borderRadius: 10,
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    button: {
        backgroundColor: '#34865C',
        borderRadius: 4,
        marginTop: 16,
        height: 60,
        width: 250,
        border: "1px solid #000",
        borderWidth: 1,
        padding: 10,
        borderRadius: 10,
        marginBottom: 20,
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
    },
    buttonText: {
        color: '#092C1A',
        fontSize: 25,
        fontStyle: 'normal',
        fontWeight: 'bold',
        textAlign: 'center',
    },
    forgotText: {
        width: 120,
        height: 80,
        color: '#C7F3D3',
        alignItems: 'center',
        justifyContent: 'center',
    },
});